### ISSUE TITLE
\ symbol is replaced with ¥

### ISSUE THREAD

**Issue by faucetlol** [mandorinn/eSix-Cafe#22]
I noticed this quite a while back and backslashes appear so irregularly it's never been a problem for me but it caused a little confusion in the e621 Discord. It's caused by the Yu Gothic UI font using the backslash codepoint as a Yen symbol - something which is apparently common for Japanese fonts prior to Unicode as a legacy thing or something like that.

![image](https://user-images.githubusercontent.com/102884856/188744752-3356892c-e4c9-4bbf-885e-85e969cb4217.png)

I don't know if you have a specific attachment to the font or if you think it's even worth changing it over this or not. `Segoe UI` looks _very_ similar and leaves the backslashes as backslashes. The only major difference I observed with Segoe UI is that bold text looks a little bolder.

**Comment by mandorinn** [comment]
In retrospect I probably should've chose a non-Japanese font for the website that has a mostly English speaking audience, fixed! 

Also no, I don't have any specific attachment, I've just been accustomed to ¥ being a backslash ever since I switched my PC's language like 4 years ago so it didn't even register as a possible issue lmaooo!
