### ISSUE TITLE
Pending approval notice doesn't show additional information

### ISSUE THREAD

**Issue by faucetlol** [mandorinn/eSix-Cafe#5]
![image](https://user-images.githubusercontent.com/102884856/163608946-c3671d54-c4d7-419a-8c34-33fe19de65f7.png)

![image](https://user-images.githubusercontent.com/102884856/163608973-716839f4-70e3-4b1f-b8b1-193d175737c7.png)

I was going to have a go at this myself, but my CSS knowledge isn't good enough to understand what's going on with the pending approval notice. (making the notice actually look good with that much text too would be another struggle)

Example:
```
<div class="notice notice-pending" id="pending-approval-notice">
      This post is pending approval. (<a href="/wiki_pages?title=about%3Amod_queue">learn more</a>)

        <p>
    It has been reviewed by 1 approver.

      1 believe it doesn't meet the quality standards.


  </p>


    </div>
```

**Comment by mandorinn** [comment]
Was about to close the other issue and release the update, but I suppose I can just leave my spiel hereeee~
Tag categories from the other issue are fixed, thanks or the heads up!

Regarding the pending notice, the way I did it is *super* jank to say the leasttttt (it works thooo lmaoo)
Basically to remove the parenthesis from the (learn more) link I set the font size of the text to 0, and used two pseudo elements to make the notice~
Since the bottom bit is wrapped in a p tag all I needed to do was set the font size for it back to normal. (and add 'flex-wrap: wrap' to make it not look terribleeeee) 

![firefox_o7Zz5gSvaO](https://user-images.githubusercontent.com/91846001/163624978-1f622346-2f20-4e69-ad5d-4da0c848ab1f.png)
