### ISSUE TITLE
Help index too long for 1366*768 screen

### ISSUE THREAD

**Issue by faucetlol** [mandorinn/eSix-Cafe#7]
The [help index](https://e621.net/help) is too long to display on smaller monitors, and because the position is fixed it can't be scrolled. I normally use a much larger monitor so I didn't notice this before:

![image](https://user-images.githubusercontent.com/102884856/163986827-f7e8faa3-c383-4627-8cb0-75741c3f2e9c.png)

**Comment by mandorinn** [comment]
Dunno why I didn't use a position of sticky instead of fixed beforeee?
I vaguely remember it causing issues but it works fine now sooooooo
Needless to say, fixed and published! Let's hope the issues I experienced before with the sticky positioning were just a fluke with the live preview or somethingggg lollll
